// import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk, Manrope } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";


const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={`${spaceGrotesk.className} bg-[#0E0E0E]`}
    >
      <head>
        <link
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" 
        rel="stylesheet" 
        />
      </head>
      <body>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  );
}
